import { IExchangeMetadata } from '../types'

export const exchanges: IExchangeMetadata[] = [
  {
    id: 'bybit',
    name: 'Bybit',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'kucoin',
    name: 'Kucoin',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: '1inch',
    name: '1inch',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'balancer',
    name: 'Balancer',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'bancor',
    name: 'Bancor',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'binance',
    name: 'Binance',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'bithumb',
    name: 'Bithumb',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'bitstamp',
    name: 'Bitstamp',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'btcturk',
    name: 'BTC Turk',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'crypto-com',
    name: 'Crypto.com',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'gate-io',
    name: 'Gate Io',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'kraken',
    name: 'Kraken',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'odos',
    name: 'Odos',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'okx',
    name: 'OkX',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'pancake-swap',
    name: 'Pancake Swap',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'para-swap',
    name: 'ParaSwap',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'paribu',
    name: 'Paribu',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'sushiswap',
    name: 'Sushi Swap',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'swissborg',
    name: 'SwissBorg',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'uniswap',
    name: 'Uniswap',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
  {
    id: 'upbit',
    name: 'UpBit',
    variants: ['branded', 'mono'],
    type: 'cex',
  },
  {
    id: 'cowswap',
    name: 'Cow Swap',
    variants: ['branded', 'mono'],
    type: 'dex',
  },
]
