import { INetworkMetadata } from '../types'

export const networks: INetworkMetadata[] = [
  {
    id: 'kujira',
    name: 'Kujira',
    variants: ['branded', 'mono'],
    nativeCoinId: 'kujira',
    shortName: 'kujira',
  },
  {
    id: 'eos',
    name: 'EOS evm',
    variants: ['branded', 'mono'],
    chainId: 17777,
    nativeCoinId: 'eos',
    shortName: 'eos',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    variants: ['branded', 'mono'],
    shortName: 'aurora',
    chainId: 1313161554,
    nativeCoinId: 'aurora-near',
  },
  {
    id: 'polygon-pos',
    name: 'Polygon',
    variants: ['branded', 'mono'],
    shortName: 'MATIC',
    chainId: 137,
    nativeCoinId: 'matic-network',
  },
  {
    id: 'cardano',
    name: 'Cardano',
    variants: ['branded', 'mono'],
    nativeCoinId: 'cardano',
    shortName: 'ada',
  },
  {
    id: 'tron',
    name: 'TRON',
    variants: ['branded', 'mono'],
    nativeCoinId: 'tron',
    shortName: 'tron',
  },
  {
    id: 'polygon-zkevm',
    name: 'Polygon zkEVM',
    variants: ['branded', 'mono'],
    chainId: 1101,
    nativeCoinId: 'ethereum',
    shortName: 'polygon',
  },
  {
    id: 'telos',
    name: 'Telos',
    variants: ['branded', 'mono'],
    chainId: 40,
    nativeCoinId: 'telos',
    shortName: 'telos',
  },
  {
    id: 'algorand',
    name: 'Algorand',
    variants: ['mono'],
    nativeCoinId: 'algorand',
    shortName: 'algo',
  },
  {
    id: 'mode',
    name: 'Mode',
    variants: ['branded', 'mono'],
    nativeCoinId: 'mode',
    shortName: 'mode',
    chainId: 3444,
  },
  {
    id: 'neon-evm',
    name: 'Neon EVM',
    variants: ['branded', 'mono'],
    chainId: 245022934,
    nativeCoinId: 'neon',
    shortName: 'neon-evm',
  },
  {
    id: 'cronos',
    name: 'Cronos',
    variants: ['branded', 'mono'],
    shortName: 'CRO',
    chainId: 25,
    nativeCoinId: 'crypto-com-chain',
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    variants: ['branded', 'mono'],
    shortName: 'Ethereum',
    chainId: 1,
    nativeCoinId: 'ethereum',
  },
  {
    id: 'starknet',
    name: 'StarkNet',
    variants: ['branded', 'mono'],
    nativeCoinId: 'starknet',
    shortName: 'starknet',
  },
  {
    id: 'kava',
    name: 'Kava',
    variants: ['branded', 'mono'],
    chainId: 2222,
    nativeCoinId: 'kava',
    shortName: 'kava',
  },
  {
    id: 'linea',
    name: 'Linea',
    variants: ['branded', 'mono'],
    chainId: 59144,
    nativeCoinId: 'ethereum',
    shortName: 'linea',
  },
  {
    id: 'filecoin',
    name: 'Filecoin',
    variants: ['branded', 'mono'],
    chainId: 314,
    nativeCoinId: 'filecoin',
    shortName: 'filecoin',
  },
  {
    id: 'zilliqa',
    name: 'Zilliqa',
    variants: ['branded', 'mono'],
    chainId: 32769,
    nativeCoinId: 'zilliqa',
    shortName: 'zilliqa',
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    variants: ['branded', 'mono'],
    nativeCoinId: 'cosmos',
    shortName: 'cosmos',
  },
  {
    id: 'stellar',
    name: 'Stellar',
    variants: ['branded', 'mono'],
    nativeCoinId: 'stellar',
    shortName: 'stellar',
  },
  {
    id: 'ronin',
    name: 'Ronin',
    variants: ['branded', 'mono'],
    shortName: 'ron',
    nativeCoinId: 'ronin',
    chainId: 202,
  },
  {
    id: 'osmosis',
    name: 'Osmosis',
    variants: ['branded', 'mono'],
    shortName: 'Osmo',
    nativeCoinId: 'osmosis',
  },
  {
    id: 'xai',
    name: 'XAI',
    variants: ['branded', 'mono'],
    nativeCoinId: 'xai-blockchain',
    shortName: 'xai',
    chainId: 66027,
  },
  {
    id: 'manta-pacific',
    name: 'Manta Pacific',
    variants: ['branded', 'mono'],
    chainId: 169,
    nativeCoinId: 'weth',
    shortName: 'manta',
  },
  {
    id: 'immutable',
    name: 'Immutable zkEVM',
    variants: ['branded', 'mono'],
    chainId: 13371,
    nativeCoinId: 'immutable-x',
    shortName: 'immutable',
  },
  {
    id: 'zora-network',
    name: 'Zora',
    variants: ['branded'],
    chainId: 7777777,
    nativeCoinId: 'weth',
    shortName: 'zora',
  },
  {
    id: 'injective',
    name: 'Injective',
    variants: ['branded', 'mono'],
    nativeCoinId: 'injective-protocol',
    shortName: 'injective',
  },
  {
    id: 'solana',
    name: 'Solana',
    variants: ['branded', 'mono'],
    shortName: 'Solana',
    nativeCoinId: 'solana',
  },
  {
    id: 'blast',
    name: 'Blast',
    variants: ['branded', 'mono'],
    chainId: 81457,
    nativeCoinId: 'blast',
    shortName: 'blast',
  },
  {
    id: 'moonbeam',
    name: 'Moonbeam',
    variants: ['branded', 'mono'],
    chainId: 1284,
    nativeCoinId: 'moonbeam',
    shortName: 'moonbeam',
  },
  {
    id: 'astar',
    name: 'Astar',
    variants: ['branded', 'mono'],
    chainId: 592,
    nativeCoinId: 'astar',
    shortName: 'astar',
  },
  {
    id: 'zksync',
    name: 'zkSync era',
    variants: ['branded', 'mono'],
    shortName: 'zkSync',
    chainId: 324,
    nativeCoinId: 'ethereum',
  },
  {
    id: 'ordinals',
    name: 'Bitcoin',
    variants: ['branded', 'mono'],
    shortName: 'Ordinals',
    nativeCoinId: 'bitcoin',
  },
  {
    id: 'juno',
    name: 'Juno',
    variants: ['branded', 'mono'],
    nativeCoinId: 'juno-network',
    shortName: 'juno',
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    variants: ['branded', 'mono'],
    nativeCoinId: 'polkadot',
    shortName: 'dot',
  },
  {
    id: 'beam',
    name: 'Beam',
    variants: ['branded', 'mono'],
    chainId: 4337,
    nativeCoinId: 'beam',
    shortName: 'beam',
  },
  {
    id: 'boba',
    name: 'Boba Network',
    variants: ['branded', 'mono'],
    chainId: 288,
    nativeCoinId: 'ethereum',
    shortName: 'boba',
  },
  {
    id: 'elrond',
    name: 'MultiversX',
    variants: ['branded', 'mono'],
    shortName: 'elrond',
    nativeCoinId: 'elrond-erd-2',
  },
  {
    id: 'celo',
    name: 'Celo',
    variants: ['branded', 'mono'],
    shortName: 'celo',
    chainId: 42220,
    nativeCoinId: 'celo',
  },
  {
    id: 'base',
    name: 'Base',
    variants: ['branded', 'mono'],
    chainId: 8453,
    nativeCoinId: 'ethereum',
    shortName: 'base',
  },
  {
    id: 'binance-smart-chain',
    name: 'BNB Smart Chain',
    variants: ['branded', 'mono'],
    shortName: 'BSC',
    chainId: 56,
    nativeCoinId: 'binancecoin',
  },
  {
    id: 'loopring',
    name: 'Loopring',
    variants: ['branded', 'mono'],
    nativeCoinId: 'loopring',
    shortName: 'loopring',
  },
  {
    id: 'fantom',
    name: 'Fantom',
    variants: ['branded', 'mono'],
    chainId: 250,
    nativeCoinId: 'fantom',
    shortName: 'fantom',
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    variants: ['branded', 'mono'],
    shortName: 'AVAX',
    chainId: 43114,
    nativeCoinId: 'avalanche-2',
  },
  {
    id: 'optimistic-ethereum',
    name: 'Optimism',
    variants: ['branded', 'mono'],
    shortName: 'Optimism',
    chainId: 10,
    nativeCoinId: 'ethereum',
  },
  {
    id: 'scroll',
    name: 'Scroll',
    variants: ['branded', 'mono'],
    nativeCoinId: 'weth',
    shortName: 'scroll',
    chainId: 53435,
  },
  {
    id: 'aptos',
    name: 'Aptos',
    variants: ['branded', 'mono'],
    nativeCoinId: 'aptos',
    shortName: 'aptos',
  },
  {
    id: 'sui',
    name: 'Sui',
    variants: ['branded', 'mono'],
    nativeCoinId: 'sui',
    shortName: 'sui',
  },
  {
    id: 'chiliz',
    name: 'Chiliz',
    variants: ['branded', 'mono'],
    chainId: 88888,
    nativeCoinId: 'chiliz',
    shortName: 'chiliz',
  },
  {
    id: 'x-layer',
    name: 'X Layer',
    variants: ['branded', 'mono'],
    nativeCoinId: 'okb',
    shortName: 'xlayer',
    chainId: 19,
  },
  {
    id: 'etherlink',
    name: 'etherlink',
    variants: ['branded', 'mono'],
    shortName: 'etherlink',
    chainId: 42793,
    nativeCoinId: 'xtz',
  },
  {
    id: 'arbitrum-one',
    name: 'Arbitrum One',
    variants: ['branded', 'mono'],
    shortName: 'Arbitrum',
    chainId: 42161,
    nativeCoinId: 'ethereum',
  },
  {
    id: 'xrp',
    name: 'XRP Ledger',
    variants: ['mono'],
    shortName: 'xrp',
    nativeCoinId: 'ripple',
  },
  {
    id: 'cosmos-hub',
    name: 'Cosmos Hub',
    variants: ['branded', 'mono'],
    nativeCoinId: 'cosmos',
    shortName: 'cosmos',
  },
  {
    id: 'metis-andromeda',
    name: 'Metis Andromeda',
    variants: ['branded', 'mono'],
    chainId: 1088,
    nativeCoinId: 'metis-token',
    shortName: 'metis',
  },
  {
    id: 'moonriver',
    name: 'Moonriver',
    variants: ['branded', 'mono'],
    shortName: 'moonriver',
    chainId: 1285,
    nativeCoinId: 'moonriver',
  },
  {
    id: 'sei-network',
    name: 'Sei Network',
    variants: ['branded', 'mono'],
    nativeCoinId: 'sei-network',
    shortName: 'sei',
    chainId: 132,
  },
  {
    id: 'litecoin',
    name: 'Litecoin',
    variants: ['branded', 'mono'],
    nativeCoinId: 'litecoin',
    shortName: 'ltc',
  },
  {
    id: 'wemix',
    name: 'Wemix',
    variants: ['branded', 'mono'],
    nativeCoinId: 'wemix',
    shortName: 'wemix',
    chainId: 111,
  },
  {
    id: 'gnosis',
    name: 'Gnosis Chain',
    variants: ['branded', 'mono'],
    chainId: 100,
    nativeCoinId: 'xDai',
    shortName: 'xdai',
  },
  {
    id: 'near-protocol',
    name: 'Near Protocol',
    variants: ['branded', 'mono'],
    shortName: 'near-protocol',
    nativeCoinId: 'near',
    chainId: 39,
  },
  {
    id: 'hedera-hashgraph',
    name: 'Hedera Hashgraph',
    variants: ['branded', 'mono'],
    shortName: 'hedera',
    chainId: 295,
    nativeCoinId: 'hedera-hashgraph',
  },
  {
    id: 'rari',
    name: 'Rari',
    variants: ['branded', 'mono'],
    nativeCoinId: 'rari',
    shortName: 'rari',
    chainId: 138001261,
  },
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    variants: ['branded', 'mono'],
    shortName: 'bitcoin',
    nativeCoinId: 'bitcoin',
  },
  {
    id: 'zetachain',
    name: 'Zeta Chain',
    variants: ['branded', 'mono'],
    chainId: 7000,
    nativeCoinId: 'zetachain',
  },
  {
    id: 'fio',
    name: 'FIO Protocol',
    variants: ['branded', 'mono'],
    shortName: 'fio',
    nativeCoinId: 'FIO',
  },
  {
    id: 'stargaze',
    name: 'Stargaze',
    variants: ['branded', 'mono'],
    nativeCoinId: 'stargaze',
    shortName: 'stargaze',
  },
  {
    id: 'iotex',
    name: 'IoTeX',
    variants: ['branded', 'mono'],
    shortName: 'iotex',
    chainId: 4689,
    nativeCoinId: 'iotex',
  },
  {
    id: 'clover',
    name: 'Clover',
    variants: ['branded', 'mono'],
    nativeCoinId: 'clover-finance',
    shortName: 'clover',
  },
  {
    id: 'gravity',
    name: 'gravity-network',
    variants: ['branded', 'mono'],
    shortName: 'gravity',
    chainId: 1625,
    nativeCoinId: 'g',
  },
  {
    id: 'lava-network',
    name: 'lava-network',
    variants: ['branded', 'mono'],
    nativeCoinId: 'lava-network',
    shortName: 'lava',
  },
  {
    id: 'neo-x',
    name: 'neo-x',
    variants: ['branded', 'mono'],
    nativeCoinId: 'neo',
    shortName: 'neox',
    chainId: 4776,
  },
  {
    id: 'abstract',
    name: 'abstract',
    variants: ['branded', 'mono'],
    nativeCoinId: 'eth',
    shortName: 'abstract',
    chainId: 1112,
  },
  {
    id: 'acala',
    name: 'Acala',
    variants: ['branded', 'mono'],
    nativeCoinId: 'acala',
    shortName: 'acala',
    chainId: 78,
  },
  {
    id: 'apex-layer',
    name: 'apex layer',
    variants: ['branded', 'mono'],
    shortName: 'apex',
  },
  {
    id: 'arbitrum-nova',
    name: 'Arbitrum Nova',
    variants: ['branded', 'mono'],
    chainId: 42170,
    nativeCoinId: 'ethereum',
    shortName: 'arbitrum-nova',
  },
  {
    id: 'bitkub-chain',
    name: 'Bitkub Chain',
    variants: ['branded', 'mono'],
    chainId: 96,
    nativeCoinId: 'bitkub-coin',
    shortName: 'bitkub',
  },
  {
    id: 'coinex-smart-chain',
    name: 'CoinEx Smart Chain',
    variants: ['branded', 'mono'],
    shortName: 'CSC',
    chainId: 52,
    nativeCoinId: 'coinex-token',
  },
  {
    id: 'conflux',
    name: 'Conflux',
    variants: ['branded', 'mono'],
    shortName: 'conflux',
    chainId: 1030,
    nativeCoinId: 'conflux-token',
  },
  {
    id: 'cronos-zkevm',
    name: 'Cronos zkEVM',
    variants: ['branded', 'mono'],
    chainId: 388,
    nativeCoinId: 'cronos-zkevm-cro',
    shortName: 'cronos',
  },
  {
    id: 'elastos',
    name: 'Elastos Smart Contract Chain',
    variants: ['branded', 'mono'],
    shortName: 'Elastos',
    chainId: 20,
    nativeCoinId: 'elastos',
  },
  {
    id: 'energy-web',
    name: 'energy web',
    variants: ['branded', 'mono'],
    shortName: 'energy',
    chainId: 246,
    nativeCoinId: 'ewt',
  },
  {
    id: 'enuls',
    name: 'enuls',
    variants: ['branded', 'mono'],
    shortName: 'enuls',
    chainId: 119,
    nativeCoinId: 'nuls',
  },
  {
    id: 'ethereum-classic',
    name: 'Ethereum Classic',
    variants: ['branded', 'mono'],
    chainId: 61,
    nativeCoinId: 'ethereum-classic',
    shortName: 'eth-classic',
  },
  {
    id: 'flare',
    name: 'flare',
    variants: ['branded', 'mono'],
    shortName: 'flare',
    chainId: 14,
    nativeCoinId: 'flr',
  },
  {
    id: 'fraxtal',
    name: 'Fraxtal',
    variants: ['branded', 'mono'],
    chainId: 252,
    nativeCoinId: 'fraxtal',
    shortName: 'fraxtal',
  },
  {
    id: 'fuse',
    name: 'Fuse',
    variants: ['branded', 'mono'],
    chainId: 122,
    nativeCoinId: 'fuse-network-token',
    shortName: 'fuse',
  },
  {
    id: 'kardia',
    name: 'kardia chain',
    variants: ['branded', 'mono'],
    shortName: 'kardia',
    chainId: 24,
    nativeCoinId: 'kai',
  },
  {
    id: 'lukso',
    name: 'Lukso',
    variants: ['branded', 'mono'],
    chainId: 42,
    nativeCoinId: 'lukso-token-2',
    shortName: 'lukso',
  },
  {
    id: 'lyra',
    name: 'lyra chain',
    variants: ['branded', 'mono'],
    shortName: 'lyra',
    chainId: 957,
    nativeCoinId: 'eth',
  },
  {
    id: 'meter',
    name: 'Meter',
    variants: ['branded', 'mono'],
    chainId: 82,
    nativeCoinId: 'meter',
    shortName: 'meter',
  },
  {
    id: 'oasys',
    name: 'Oasys',
    variants: ['branded', 'mono'],
    chainId: 248,
    nativeCoinId: 'oasys',
    shortName: 'oasys',
  },
  {
    id: 'okex-chain',
    name: 'OKT Chain',
    variants: ['branded', 'mono'],
    shortName: 'OKEx',
    chainId: 66,
    nativeCoinId: 'oec-token',
  },
  {
    id: 'rollux',
    name: 'Rollux',
    variants: ['branded', 'mono'],
    chainId: 570,
    nativeCoinId: 'syscoin',
    shortName: 'rollux',
  },
  {
    id: 'rootstock',
    name: 'Rootstock RSK',
    variants: ['branded', 'mono'],
    chainId: 30,
    nativeCoinId: 'rootstock',
    shortName: 'rootstock',
  },
  {
    id: 'shiden',
    name: 'shiden',
    variants: ['branded', 'mono'],
    shortName: 'shiden',
    chainId: 336,
    nativeCoinId: 'sdn',
  },
  {
    id: 'shimmer-evm',
    name: 'shimmer evm',
    variants: ['branded', 'mono'],
    shortName: 'shimmer',
    chainId: 148,
    nativeCoinId: 'smr',
  },
  {
    id: 'songbird',
    name: 'Songbird',
    variants: ['branded', 'mono'],
    chainId: 19,
    nativeCoinId: 'songbird',
    shortName: '19',
  },
  {
    id: 'step',
    name: 'step',
    variants: ['branded', 'mono'],
    shortName: 'step',
    chainId: 1234,
    nativeCoinId: 'step',
  },
  {
    id: 'sys',
    name: 'syscoin',
    variants: ['branded', 'mono'],
    shortName: 'sys',
    chainId: 57,
    nativeCoinId: 'sys',
  },
  {
    id: 'theta',
    name: 'Theta',
    variants: ['branded', 'mono'],
    chainId: 361,
    nativeCoinId: 'theta-token',
    shortName: 'theta',
  },
  {
    id: 'thundercore',
    name: 'ThunderCore',
    variants: ['branded', 'mono'],
    chainId: 108,
    nativeCoinId: 'thunder-token',
    shortName: 'thunder',
  },
  {
    id: 'ubiq',
    name: 'ubiq',
    variants: ['branded', 'mono'],
    shortName: 'ubiq',
    chainId: 8,
    nativeCoinId: 'ubq',
  },
  {
    id: 'ultron',
    name: 'Ultron',
    variants: ['branded', 'mono'],
    chainId: 1231,
    nativeCoinId: 'ultron',
    shortName: 'ultron',
  },
  {
    id: 'velas',
    name: 'Velas',
    variants: ['branded', 'mono'],
    shortName: 'velas',
    chainId: 106,
    nativeCoinId: 'velas',
  },
  {
    id: 'tomochain',
    name: 'Viction',
    variants: ['branded', 'mono'],
    chainId: 88,
    nativeCoinId: 'tomochain',
    shortName: 'viction',
  },
  {
    id: 'xdc',
    name: 'xdc network',
    variants: ['branded', 'mono'],
    shortName: 'xdc',
    chainId: 50,
    nativeCoinId: 'xdc',
  },
  {
    id: 'zyx',
    name: 'zyx',
    variants: ['branded', 'mono'],
    shortName: 'zyx',
    chainId: 55,
    nativeCoinId: 'zyx',
  },
  {
    id: 'kuchain',
    name: 'kuchain',
    variants: ['branded', 'mono'],
    shortName: 'kuchain',
    chainId: 321,
    nativeCoinId: 'kcs',
  },
  {
    id: 'dogechain',
    name: 'Dogechain',
    variants: ['branded'],
    chainId: 2000,
    nativeCoinId: 'dogechain',
    shortName: 'dogechain',
  },
  {
    id: 'hubblenet',
    name: 'hubble exchange',
    variants: ['branded', 'mono'],
    shortName: 'hubble',
    chainId: 1992,
    nativeCoinId: 'usdc',
  },
  {
    id: 'milkomeda-a1',
    name: 'milkomeda A1',
    variants: ['branded', 'mono'],
    shortName: 'milkomeda',
    chainId: 2002,
    nativeCoinId: 'mALGO',
  },
  {
    id: 'milkomeda-c1',
    name: 'milkomeda C1',
    variants: ['branded', 'mono'],
    shortName: 'milkomeda',
    chainId: 2001,
    nativeCoinId: 'mADA',
  },
  {
    id: 'reya',
    name: 'reya',
    variants: ['branded', 'mono'],
    shortName: 'reya',
    chainId: 1729,
    nativeCoinId: 'eth',
  },
  {
    id: 'tenet',
    name: 'Tenet',
    variants: ['branded', 'mono'],
    chainId: 1559,
    nativeCoinId: 'tenet-1b000f7b-59cb-4e06-89ce-d62b32d362b9',
    shortName: 'tenet',
  },
  {
    id: 'bouncebit',
    name: 'BounceBit',
    variants: ['branded', 'mono'],
    chainId: 6001,
    nativeCoinId: 'bouncebit',
    shortName: 'bounce',
  },
  {
    id: 'mantle',
    name: 'Mantle',
    variants: ['branded', 'mono'],
    chainId: 5000,
    nativeCoinId: 'mantle',
    shortName: 'mantle',
  },
  {
    id: 'nahmii',
    name: 'Nahmii',
    variants: ['branded', 'mono'],
    shortName: 'nahmii',
    chainId: 4061,
    nativeCoinId: 'nahmii',
  },
  {
    id: 'tombchain',
    name: 'Tombchain',
    variants: ['branded'],
    shortName: 'tomb',
    chainId: 6969,
    nativeCoinId: 'tomb',
  },
  {
    id: 'hubble-exchange',
    name: 'hubble exchange',
    variants: ['branded', 'mono'],
    shortName: 'hubble',
    chainId: 1992,
    nativeCoinId: 'usdc',
  },
  {
    id: 'kucoin',
    name: 'kucoin',
    variants: ['branded', 'mono'],
    shortName: 'kucoin',
    nativeCoinId: 'kcs',
  },
  {
    id: 'zeta',
    name: 'zeta chain',
    variants: ['branded', 'mono'],
    shortName: 'zeta',
    chainId: 7000,
    nativeCoinId: 'zeta',
  },
  {
    id: 'zeta-chain',
    name: 'zeta chain',
    variants: ['branded', 'mono'],
    shortName: 'zeta',
    chainId: 7000,
    nativeCoinId: 'zeta',
  },
  {
    id: 'bob',
    name: 'Bob',
    variants: ['branded', 'mono'],
    shortName: 'bob',
    chainId: 60808,
    nativeCoinId: 'eth',
  },
  {
    id: 'klay-token',
    name: 'Kaia',
    variants: ['branded', 'mono'],
    shortName: 'kaia',
    chainId: 8217,
    nativeCoinId: 'kaia',
  },
  {
    id: 'kakarot',
    name: 'Kakarot',
    variants: ['branded', 'mono'],
    shortName: 'kakarot',
    nativeCoinId: 'eth',
  },
  {
    id: 'karura',
    name: 'Karura',
    variants: ['branded', 'mono'],
    shortName: 'karura',
    chainId: 686,
    nativeCoinId: 'karura',
  },
  {
    id: 'soneium',
    name: 'Soneium',
    variants: ['branded', 'mono'],
    shortName: 'soneium',
    chainId: 1946,
    nativeCoinId: 'eth',
  },
  {
    id: 'kroma',
    name: 'kroma',
    variants: ['branded', 'mono'],
    shortName: 'kroma',
    chainId: 255,
    nativeCoinId: 'eth',
  },
  {
    id: 'l3x',
    name: 'L3X Protocol',
    variants: ['branded', 'mono'],
    shortName: 'l3x',
    chainId: 12324,
    nativeCoinId: 'eth',
  },
  {
    id: 'lightlink',
    name: 'LightLink',
    variants: ['branded', 'mono'],
    shortName: 'lightlink',
    chainId: 1890,
    nativeCoinId: 'ethereum',
  },
  {
    id: 'lisk',
    name: 'Lisk',
    variants: ['branded', 'mono'],
    shortName: 'lisk',
    chainId: 1135,
    nativeCoinId: 'lisk',
  },
  {
    id: 'lycan',
    name: 'Lycan',
    variants: ['branded', 'mono'],
    shortName: 'lycan',
    chainId: 721,
    nativeCoinId: 'lyc',
  },
  {
    id: 'arweave',
    name: 'Arweave',
    variants: ['branded', 'mono'],
    shortName: 'arweave',
    nativeCoinId: 'ar',
  },
  {
    id: 'fluence',
    name: 'Fluence',
    variants: ['branded', 'mono'],
    shortName: 'fluence',
    chainId: 9999999,
    nativeCoinId: 'flt',
  },
  {
    id: 'harmony',
    name: 'Harmony One',
    variants: ['branded', 'mono'],
    shortName: 'one',
    chainId: 1666600000,
    nativeCoinId: 'one',
  },
  {
    id: 'optopia',
    name: 'Optopia AI',
    variants: ['branded', 'mono'],
    shortName: 'optopia',
    chainId: 62050,
    nativeCoinId: 'eth',
  },
  {
    id: 'orderly',
    name: 'Orderly',
    variants: ['branded', 'mono'],
    shortName: 'orderly',
    chainId: 291,
    nativeCoinId: 'eth',
  },
  {
    id: 'moonbase',
    name: 'moonbase',
    variants: ['branded', 'mono'],
    shortName: 'moonbase',
    chainId: 1287,
  },
  {
    id: 'unichain',
    name: 'Unichain',
    variants: ['branded', 'mono'],
    shortName: 'uni',
    chainId: 130,
    nativeCoinId: 'eth',
  },
  {
    id: 'lumio',
    name: 'Super Lumio',
    variants: ['branded'],
    shortName: 'lumio',
    chainId: 8866,
    nativeCoinId: 'eth',
  },
  {
    id: 'mooonbase-alpha',
    name: 'Moonbase Alpha',
    variants: ['branded', 'mono'],
    shortName: 'moonbase alpha',
    chainId: 1287,
  },
  {
    id: 'taiko',
    name: 'Taiko',
    variants: ['branded', 'mono'],
    shortName: 'taiko',
    chainId: 167000,
    nativeCoinId: 'taiko',
  },
  {
    id: 'diode',
    name: 'Diode',
    variants: ['branded', 'mono'],
    shortName: 'diode',
    chainId: 15,
    nativeCoinId: 'diode',
  },
  {
    id: 'edgeless',
    name: 'Edgeless Network',
    variants: ['branded', 'mono'],
    shortName: 'edgeless',
    chainId: 2026,
    nativeCoinId: 'eweth',
  },
  {
    id: 'lens',
    name: 'Lens',
    variants: ['branded', 'mono'],
    shortName: 'lens',
  },
  {
    id: 'world',
    name: 'World Chain',
    variants: ['branded', 'mono'],
    shortName: 'world',
    chainId: 480,
    nativeCoinId: 'eth',
  },
  {
    id: 'botanix',
    name: 'Botanix',
    variants: ['branded', 'mono'],
    shortName: 'botanix',
    chainId: 3637,
    nativeCoinId: 'btc',
  },
  {
    id: 'corn',
    name: 'Corn',
    variants: ['branded', 'mono'],
    shortName: 'corn',
    chainId: 21000000,
    nativeCoinId: 'btc',
  },
  {
    id: 'mantra',
    name: 'Mantra Chain',
    variants: ['branded', 'mono'],
    shortName: 'mantra',
  },
  {
    id: 'hemi',
    name: 'Hemi',
    variants: ['branded', 'mono'],
    shortName: 'hemi',
    chainId: 743111,
  },
  {
    id: 'lumia',
    name: 'Lumia',
    variants: ['branded', 'mono'],
    shortName: 'lumia',
    chainId: 1952959480,
  },
  {
    id: 'sonic',
    name: 'Sonic',
    variants: ['branded', 'mono'],
    shortName: 'sonic',
    chainId: 146,
    nativeCoinId: 'sonic-3',
  },
  {
    id: 'super-seed',
    name: 'Super Seed',
    variants: ['branded', 'mono'],
    shortName: 'Super Seed',
    chainId: 53302,
  },
  {
    id: 'vanar',
    name: 'Vanar',
    variants: ['branded', 'mono'],
    shortName: 'vanar',
    chainId: 2040,
  },
  {
    id: 'wax',
    name: 'WAX',
    variants: ['branded', 'mono'],
    shortName: 'wax',
    nativeCoinId: 'wax',
  },
  {
    id: 'rei',
    name: 'Rei',
    variants: ['branded', 'mono'],
    shortName: 'rei',
    chainId: 47805,
  },
  {
    id: 'mint',
    name: 'Mint',
    variants: ['branded', 'mono'],
    shortName: 'mint',
    chainId: 185,
    nativeCoinId: 'weth',
  },
  {
    id: 'monad',
    name: 'Monad',
    variants: ['branded', 'mono'],
    shortName: 'monad',
    chainId: 143,
    nativeCoinId: 'monad',
  },
  {
    id: 'silicon',
    name: 'Silicon',
    variants: ['branded', 'mono'],
    shortName: 'silicon',
    chainId: 2355,
    nativeCoinId: 'eth',
  },
  {
    id: 'treasure',
    name: 'Treasure',
    variants: ['branded', 'mono'],
    shortName: 'treasure',
    chainId: 61166,
    nativeCoinId: 'magic',
  },
]
