import { INetworkMetadata } from '../types'

export const networks: INetworkMetadata[] = [
  {
    id: 'kujira',
    name: 'Kujira',
    variants: ['branded', 'mono'],
  },
  {
    id: 'eos',
    name: 'EOS',
    variants: ['branded', 'mono'],
  },
  {
    id: 'aurora',
    name: 'Aurora',
    shortname: 'aurora',
    variants: ['branded', 'mono'],
  },
  {
    id: 'polygon-pos',
    name: 'Polygon',
    shortname: 'MATIC',
    variants: ['branded', 'mono'],
  },
  {
    id: 'cardano',
    name: 'Cardano',
    variants: ['branded', 'mono'],
  },
  {
    id: 'tron',
    name: 'TRON',
    variants: ['branded', 'mono'],
  },
  {
    id: 'polygon-zkevm',
    name: 'Polygon zkEVM',
    variants: ['branded', 'mono'],
  },
  {
    id: 'telos',
    name: 'Telos',
    variants: ['branded', 'mono'],
  },
  {
    id: 'algorand',
    name: 'Algorand',
    variants: ['mono'],
  },
  {
    id: 'mode',
    name: 'Mode',
    variants: ['branded', 'mono'],
  },
  {
    id: 'neon-evm',
    name: 'Neon EVM',
    variants: ['branded', 'mono'],
  },
  {
    id: 'cronos',
    name: 'Cronos',
    shortname: 'CRO',
    variants: ['branded', 'mono'],
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    shortname: 'Ethereum',
    variants: ['branded', 'mono'],
  },
  {
    id: 'starknet',
    name: 'StarkNet',
    variants: ['branded', 'mono'],
  },
  {
    id: 'kava',
    name: 'Kava',
    variants: ['branded', 'mono'],
  },
  {
    id: 'linea',
    name: 'Linea',
    variants: ['branded', 'mono'],
  },
  {
    id: 'filecoin',
    name: 'Filecoin',
    variants: ['branded', 'mono'],
  },
  {
    id: 'zilliqa',
    name: 'Zilliqa',
    variants: ['branded', 'mono'],
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    variants: ['branded', 'mono'],
  },
  {
    id: 'stellar',
    name: 'Stellar',
    variants: ['branded', 'mono'],
  },
  {
    id: 'ronin',
    name: 'Ronin',
    shortname: 'ron',
    variants: ['branded', 'mono'],
  },
  {
    id: 'osmosis',
    name: 'Osmosis',
    shortname: 'Osmo',
    variants: ['branded', 'mono'],
  },
  {
    id: 'xai',
    name: 'XAI',
    variants: ['branded', 'mono'],
  },
  {
    id: 'manta-pacific',
    name: 'Manta Pacific',
    variants: ['branded', 'mono'],
  },
  {
    id: 'immutable',
    name: 'Immutable zkEVM',
    variants: ['branded', 'mono'],
  },
  {
    id: 'zora-network',
    name: 'Zora',
    nativeCoinId: 'weth',
    chainId: 7777777,
    variants: ['branded'],
  },
  {
    id: 'injective',
    name: 'Injective',
    variants: ['branded', 'mono'],
  },
  {
    id: 'solana',
    name: 'Solana',
    shortname: 'Solana',
    variants: ['branded', 'mono'],
  },
  {
    id: 'blast',
    name: 'Blast',
    variants: ['branded', 'mono'],
  },
  {
    id: 'moonbeam',
    name: 'Moonbeam',
    variants: ['branded', 'mono'],
  },
  {
    id: 'astar',
    name: 'Astar',
    variants: ['branded', 'mono'],
  },
  {
    id: 'zksync',
    name: 'zkSync',
    shortname: 'zkSync',
    variants: ['branded', 'mono'],
  },
  {
    id: 'ordinals',
    name: 'Bitcoin',
    shortname: 'Ordinals',
    nativeCoinId: 'bitcoin',
    variants: ['branded', 'mono'],
  },
  {
    id: 'juno',
    name: 'Juno',
    variants: ['branded', 'mono'],
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    variants: ['branded', 'mono'],
  },
  {
    id: 'beam',
    name: 'Beam',
    variants: ['branded', 'mono'],
  },
  {
    id: 'boba',
    name: 'Boba Network',
    variants: ['branded', 'mono'],
  },
  {
    id: 'elrond',
    name: 'MultiversX',
    shortname: 'elrond',
    nativeCoinId: 'elrond-erd-2',
    variants: ['branded', 'mono'],
  },
  {
    id: 'celo',
    name: 'Celo',
    shortname: 'celo',
    variants: ['branded', 'mono'],
  },
  {
    id: 'base',
    name: 'Base',
    variants: ['branded', 'mono'],
  },
  {
    id: 'binance-smart-chain',
    name: 'BNB Smart Chain',
    shortname: 'BSC',
    variants: ['branded', 'mono'],
  },
  {
    id: 'loopring',
    name: 'Loopring',
    variants: ['branded', 'mono'],
  },
  {
    id: 'fantom',
    name: 'Fantom',
    variants: ['branded', 'mono'],
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    shortname: 'AVAX',
    variants: ['branded', 'mono'],
  },
  {
    id: 'optimistic-ethereum',
    name: 'Optimism',
    shortname: 'Optimism',
    nativeCoinId: 'ethereum',
    chainId: 10,
    variants: ['branded', 'mono'],
  },
  {
    id: 'scroll',
    name: 'Scroll',
    variants: ['branded', 'mono'],
  },
  {
    id: 'aptos',
    name: 'Aptos',
    variants: ['branded', 'mono'],
  },
  {
    id: 'sui',
    name: 'Sui',
    variants: ['branded', 'mono'],
  },
  {
    id: 'chiliz',
    name: 'Chiliz',
    variants: ['branded', 'mono'],
  },
  {
    id: 'x-layer',
    name: 'X Layer',
    variants: ['branded', 'mono'],
  },
  {
    id: 'etherlink',
    name: 'etherlink',
    shortname: 'etherlink',
    variants: ['branded', 'mono'],
  },
  {
    id: 'arbitrum-one',
    name: 'Arbitrum One',
    shortname: 'Arbitrum',
    nativeCoinId: 'ethereum',
    chainId: 42161,
    variants: ['branded', 'mono'],
  },
  {
    id: 'xrp',
    name: 'XRP Ledger',
    shortname: 'xrp',
    nativeCoinId: 'ripple',
    variants: ['mono'],
  },
  {
    id: 'cosmos-hub',
    name: 'Cosmos Hub',
    nativeCoinId: 'cosmos',
    variants: ['branded', 'mono'],
  },
  {
    id: 'metis-andromeda',
    name: 'Metis Andromeda',
    nativeCoinId: 'metis-token',
    chainId: 1088,
    variants: ['branded', 'mono'],
  },
  {
    id: 'moonriver',
    name: 'Moonriver',
    shortname: 'moonriver',
    nativeCoinId: 'moonriver',
    chainId: 1285,
    variants: ['branded', 'mono'],
  },
  {
    id: 'sei-network',
    name: 'Sei Network',
    nativeCoinId: 'sei-network',
    variants: ['branded', 'mono'],
  },
  {
    id: 'litecoin',
    name: 'Litecoin',
    nativeCoinId: 'litecoin',
    variants: ['branded', 'mono'],
  },
  {
    id: 'wemix',
    name: 'Wemix',
    nativeCoinId: 'wemix',
    variants: ['branded', 'mono'],
  },
  {
    id: 'gnosis',
    name: 'Gnosis Chain',
    nativeCoinId: 'xDai',
    variants: ['branded', 'mono'],
  },
  {
    id: 'near-protocol',
    name: 'Near Protocol',
    shortname: 'near-protocol',
    nativeCoinId: 'near',
    variants: ['branded', 'mono'],
  },
  {
    id: 'hedera-hashgraph',
    name: 'Hedera Hashgraph',
    shortname: 'hedera',
    nativeCoinId: 'hedera-hashgraph',
    chainId: 295,
    variants: ['branded', 'mono'],
  },
  {
    id: 'rari',
    name: 'Rari',
    nativeCoinId: 'rari',
    variants: ['branded', 'mono'],
  },
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    shortname: 'bitcoin',
    nativeCoinId: 'bitcoin',
    variants: ['branded', 'mono'],
  },
  {
    id: 'zetachain',
    name: 'Zeta Chain',
    nativeCoinId: 'zetachain',
    chainId: 7000,
    variants: ['branded', 'mono'],
  },
  {
    id: 'fio',
    name: 'FIO Protocol',
    shortname: 'fio',
    nativeCoinId: 'FIO',
    variants: ['branded', 'mono'],
  },
  {
    id: 'stargaze',
    name: 'Stargaze',
    nativeCoinId: 'stargaze',
    variants: ['branded', 'mono'],
  },
  {
    id: 'iotex',
    name: 'IoTeX',
    shortname: 'iotex',
    nativeCoinId: 'iotex',
    chainId: 4689,
    variants: ['branded', 'mono'],
  },
  {
    id: 'clover',
    name: 'Clover',
    nativeCoinId: 'clover-finance',
    variants: ['branded', 'mono'],
  },
  {
    id: 'gravity',
    name: 'gravity-network',
    variants: ['branded', 'mono'],
  },
  {
    id: 'lava-network',
    name: 'lava-network',
    variants: ['branded', 'mono'],
  },
  {
    id: 'neo-x',
    name: 'neo-x',
    variants: ['branded', 'mono'],
  },
  {
    id: 'abstract',
    name: 'abstract',
    variants: ['branded', 'mono'],
  },
  {
    id: 'acala',
    name: 'Acala',
    nativeCoinId: 'acala',
    variants: ['branded', 'mono'],
  },
  {
    id: 'apex-layer',
    name: 'apex layer',
    variants: ['branded', 'mono'],
  },
  {
    id: 'arbitrum-nova',
    name: 'Arbitrum Nova',
    nativeCoinId: 'ethereum',
    chainId: 42170,
    variants: ['branded', 'mono'],
  },
  {
    id: 'bitkub-chain',
    name: 'Bitkub Chain',
    nativeCoinId: 'bitkub-coin',
    chainId: 96,
    variants: ['branded', 'mono'],
  },
]
